### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by rocksdanister** [the-halfbloodprince/GalaxyM1199#1]
Hi, 

I like this project and it would look great as a dynamic wallpaper for my software: 
https://github.com/rocksdanister/lively

If you are interested in others using this work, can you add a license to this project?

**Comment by the-halfbloodprince** [comment]
Hey @rocksdanister sure, I will add the license asap, feel free to use it as you want.

**Comment by rocksdanister** [comment]
thanks 🥳
